export const svgSelectors = {
    shadow: "#tail-shadow, #paw-left-shadow, #paw-right-shadow, #body-back-shadow, #body-front-shadow, #neck-shadow, #paws-front-left-shadow, #paws-front-right-shadow, #ear-left-outside-shadow, #ear-left-inside-shadow, #ear-right-inside-shadow, #head-shadow-left",
    furOnlyStroke:"#eye-left-shadow, #eye-right-shadow, #mouth, #whisker-left-1, #whisker-left-2, #whisker-left-3, #whisker-right-1, #whisker-right-2, #whisker-right-3",
    furFillAndStroke:"#head, #ear-left-outside, #ear-right-outside, #body-front, #body-back, #paw-left, #paw-right, #tail",
    eyesFill:"#eye-left-color, #eye-right-color",
    linesPattern:"#tail-linePattern00, #tail-linePattern01, #tail-linePattern02, #tail-linePattern03, #tail-linePattern04, #tail-linePattern05, #body-back-linePattern00, #body-back-linePattern01, #body-back-linePattern02, #body-back-linePattern03, #body-back-linePattern04, #body-back-linePattern05, #body-back-linePattern06, #body-back-linePattern07, #body-front-linePattern00, #body-front-linePattern01, #body-front-linePattern02, #body-front-linePattern03, #body-front-linePattern04, #body-front-linePattern05, #body-front-linePattern06, #body-front-linePattern07, #body-front-linePattern08, #body-front-linePattern09, #body-front-linePattern10, #body-front-linePattern11, #body-front-linePattern12, #body-front-linePattern13, #body-front-linePattern14, #body-front-linePattern15, #body-front-linePattern16, #head-linePattern00, #head-linePattern01, #head-linePattern02, #head-linePattern03, #head-linePattern04, #head-linePattern05, #head-linePattern06, #head-linePattern07, #head-linePattern08, #ear-left-linePattern, #ear-right-linePattern",
    colorAndWhitePattern: "#tail-cwPattern, #paw-left-back-cwPattern, #paw-right-back-cwPattern, #paw-front-left-cwPattern, #paw-front-right-cwPattern, #body-front-cwPattern, #body-back-cwPattern, #head-cwPattern",
    siamesePattern: "#tail-siamesePattern, #paw-left-back-siamesePattern, #paw-right-back-siamesePattern, #leg-front-left-siamesePattern, #leg-front-right-siamesePattern, #ear-left-siamesePattern, #ear-right-siamesePattern, #head-siamesePattern",
    tricolorPatternYellow: "#tail-tricolorPattern00, #tail-tricolorPattern01, #tail-tricolorPattern02, #back-left-tricolorPattern, #back-right-tricolorPattern, #body-front-tricolorPattern00, #body-front-tricolorPattern01, #ear-left-outside-tricolorPattern, #head-tricolorPattern00, #head-tricolorPattern01",
    tricolorPatternBlack: "#tail-tricolorPattern-black00, #tail-tricolorPattern-black01, #tail-tricolorPattern-black02, #tail-tricolorPattern-black03, #back-left-tricolorPattern-black, #back-right-tricolorPattern-black, #body-front-tricolorPattern-black00, #body-front-tricolorPattern-black01, #ear-right-outside-tricolorPattern-black, #head-tricolorPattern-black",
    pupilContracted: ".pupil-contracted",
    pupilNormal: ".pupil-normal",
    pupilExpanded: ".pupil-expanded",
    baseNecklace: "#necklace-base",
    roundNecklace: "#necklace-round, #necklace-round-light",
    heartNecklace: "#necklace-heart, #necklace-heart-light",
    ribbonNecklace: "#necklace-ribbon00, #necklace-ribbon01, #necklace-ribbon02",
    necklaceText: "#necklace-text",
    topHatSelector: "#tophat-00, #tophat-01",
    partyHatSelector: "#party-color01, #party-color02, #party-color03",
}